#!/bin/bash

# Had to remove echo because some SFTP clients would fail.
# echo "Initializing SUB Plugins..."

# Get the current directory of this script, and eval the sub command
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
eval "$($DIR/sub init -)"

_SUB_ROOT="$DIR/.."

# Get all Sub Plugin Root File Paths
_SUB_PLUGIN_ROOTS=$(ls $_SUB_ROOT/../plugins/)

for _PLUGIN_ROOT in ${_SUB_PLUGIN_ROOTS[@]}
do
	_PLUGIN_NAME=$(basename $_PLUGIN_ROOT)

	if [ "$_PLUGIN_NAME" != "blank.skel" ] && [ "$_PLUGIN_NAME" != "*" ]
	then	
		eval "$($_SUB_ROOT/../plugins/$PLUGIN_NAME/bin/$PLUGIN_NAME init -)"
	fi
done
